CREATE TABLE IF NOT EXISTS assets_kapling (
    id SERIAL PRIMARY KEY,
    name VARCHAR(255),
    code VARCHAR(50),
    category VARCHAR(100),
    luas VARCHAR(50),
    status VARCHAR(50),
    location TEXT,
    coordinates VARCHAR(100),
    map_boundary TEXT,
    area VARCHAR(100),
    occupant_name VARCHAR(100),
    occupant_rank VARCHAR(50),
    occupant_nrp VARCHAR(50),
    occupant_title VARCHAR(100),
    jenis_bmn VARCHAR(100),
    kode_barang VARCHAR(50),
    nup VARCHAR(50),
    nama_barang VARCHAR(255),
    kondisi VARCHAR(50),
    luas_tanah_seluruhnya VARCHAR(50),
    tanah_yg_telah_bersertifikat VARCHAR(50),
    tanah_yg_belum_bersertifikat VARCHAR(50),
    tanggal_perolehan VARCHAR(50),
    nilai_perolehan NUMERIC,
    no_sertifikat VARCHAR(100),
    tgl_sertifikat VARCHAR(50),
    standar_satuan VARCHAR(50),
    alamat_detail TEXT,
    kecamatan VARCHAR(100),
    kabupaten VARCHAR(100),
    provinsi VARCHAR(100),
    keterangan_bmn TEXT,
    kode_kota VARCHAR(50),
    no_psp VARCHAR(100),
    tgl_psp VARCHAR(50),
    rt_rw VARCHAR(50),
    kelurahan_desa VARCHAR(100),
    folder_id INTEGER,
    created_at TIMESTAMP DEFAULT NOW(),
    updated_at TIMESTAMP DEFAULT NOW()
);
